train:
    epoch: 1000
    snapshot_interval: 2000
    batchsize: 4
    validsize: 12

dataset:
    extension: ".png"
    train_image_size: 348
    valid_image_size: 512
    color_space: "rgb"
    line_space: "rgb"
    line_method: ["xdog", "pencil", "blend", "digital"]
    src_perturbation: 0.5
    tgt_perturbation: 0.2

model:
    generator:
        in_ch: 3
        lr: 0.0001
        b1: 0.5
        b2: 0.99
        mode: "train"
    discriminator:
        lr: 0.0002
        b1: 0.5
        b2: 0.99
        mode: "train"
    vgg:
        mode: "eval"

loss:
    content: 10.0
    adv: 1.0
    perceptual: 10.0
    style: 50.0